### PR TITLE
Add Maniac PVR section

### PR DESCRIPTION
**Pull request by BigNoid**
Cherry picked the relevant commits.
Could you double check @manijak ?
Ping @zag2me

### CODE REVIEW

**Comment by zag2me** [comment]
Tested and works well as far as I can see on my laptop. I had a look at the orange colour scheme as I prefer the that option, again working well.

image1

Both myself and @jalle19 have been running this on our main setups for a while now. In my opinion, this is the best UI out there for PVR based on the well tested Dreambox interface.

**Comment by BigNoid** [comment]
Thx for testing @zag2me

**Comment by manijak** [comment]
Just tested on my Mac and my two other media-centers. Perfect 1-to-1 copy :) 
Everything works and looks as it should. Great that you managed to include the entire mod. Thanks!

**Comment by BigNoid** [comment]
Great. Thx @manijak

**Pull request merged**
