### PR TITLE
don't disable hide fanart in fullscreen osd option when no visualizat…

### PR DESCRIPTION
**Pull request by jpoppe**
…ion is selected

This allows to enable fullscreen artwork with for example artist slideshow and no
visualization selected.

### CODE REVIEW

**Comment by BigNoid** [comment]
This is not needed. That setting is only for blending fanart with the visualisation. The first setting is for fullscreen fanart.

**Comment by jpoppe** [comment]
Thanks for your fast reply! When you disable the full screen artwork option when you have visualizations enabled and leave it disabled when you disable the music visualization (when you set it to none) the artist slideshow shows for me a black screen at the music visualization screen.

**Comment by BigNoid** [comment]
Should be fixed with 36b7dd0f4d5735c979298edfe710d2aef9e7dedc

**Comment by jpoppe** [comment]
Thanks!

**Pull request closed without merging**
